# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.yaml
openapi: "3.1.0"
info:
  title: "asd"
  version: "1" 
paths:
# ----------------------------------------  
  /api/carts/:
    post:
      summary: asd
      tags:
        - Carts
      security:
        - bearerAuth: []             
# ----------------------------------------
  /api/carts/{cid}:
    get:
      summary: Este servicio obtiene un carrito a partir de su uuid (identificador único autogenerado) 
      tags:
        - Carts
      security:
        - bearerAuth: []
      parameters:
        - name: cid
          in: path
          required: true
          description: El id del carrito a buscar
          schema:
            $type: string
      responses:
        "200":
          description: Get cart succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: 
                    type: string
                    description: success
                    example: success
                  payload:                 
                    $ref: '#components/schemas/Cart'   
        "401":
          description: Unauthorized request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string                  
                    description: Mensaje del tipo de estatus
                    example: error
                  payload:  
                    type: string              
                    description: Mensaje para el tipo de error
                    example: "Error: no auth token"
        "404":
          description: Cart not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string                  
                    description: Mensaje del tipo de estatus
                    example: error
                  payload:  
                    type: string              
                    description: Mensaje para el tipo de error
                    example: Cart not found
        "500":
          description: Server Error
    put:
      summary: Este servicio actualiza un carrito a partir de su uuid (identificador único autogenerado) 
      tags:
        - Carts
      security:
        - bearerAuth: []
      parameters:
        - name: pid
          in: path
          required: true
          description: El id del producto a modificar
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#components/requestBodies/updateProduct'
      responses:
        "200":
          description: E
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Cart'
        "401":
          description: Unauthorized request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string                  
                    description: Mensaje del tipo de estatus
                    example: error
                  payload:  
                    type: string              
                    description: Mensaje para el tipo de error
                    example: "Error: no auth token"                
    delete:
      summary: Este servicio elimina un carrito de compras a partir de su uuid (identificador único autogenerado)
      tags: 
        - Carts
      security:
        - bearerAuth: []
      parameters:
        - name: cid
          in: path
          required: true
          description: El id del carrito a eliminar
          schema:
            $type: string
      responses:
        "200":
          description: Cart deleted succesfully
        "401":
          description: Unauthorized request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string                  
                    description: Mensaje del tipo de estatus
                    example: error
                  payload:  
                    type: string              
                    description: Mensaje para el tipo de error
                    example: "Error: no auth token"          
        "404":
          description: Cart not found, incorrect id
        "500":
          description: Server error
# ----------------------------------------
  /api/carts/{cid}/products/{pid}:
    post:
      summary: Este servicio agrega un producto con su id (pid) al carrito con el id (cid)
      tags:
        - Carts
      security:
        - bearerAuth: []
      parameters:
        - name: pid
          in: path
          required: true
          description: El id del producto a modificar
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#components/requestBodies/updateCart'
      responses:
        "200":
          description: E
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Cart'
        "401":
          description: Unauthorized request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string                  
                    description: Mensaje del tipo de estatus
                    example: error
                  payload:  
                    type: string              
                    description: Mensaje para el tipo de error
                    example: "Error: no auth token"                
    put:
      summary: Este servicio obtiene un carrito a partir de su uuid (identificador único autogenerado) 
      tags:
        - Carts
      security:
        - bearerAuth: []
      parameters:
        - name: cid
          in: path
          required: true
          description: El id del carrito a buscar
          schema:
            $type: string
      responses:
        "200":
          description: E
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Cart'
        "401":
          description: Unauthorized request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string                  
                    description: Mensaje del tipo de estatus
                    example: error
                  payload:  
                    type: string              
                    description: Mensaje para el tipo de error
                    example: "Error: no auth token"                
        "404":
          description: No auth token provided
    delete:
      summary: Este servicio elimina un carrito de compras a partir de su uuid (identificador único autogenerado)
      tags: 
        - Carts
      security:
        - bearerAuth: []
      parameters:
        - name: cid
          in: path
          required: true
          description: El id del carrito a eliminar
          schema:
            $type: string
      responses:
        "200":
          description: Cart deleted succesfully
        "401":
          description: Unauthorized request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string                  
                    description: Mensaje del tipo de estatus
                    example: error
                  payload:  
                    type: string              
                    description: Mensaje para el tipo de error
                    example: "Error: no auth token"          
        "404":
          description: Cart not found, incorrect id
        "500":
          description: Server error             
# ----------------------------------------
  /api/carts/{cid}/purchase:
    post:
      summary: asd
      tags:
        - Carts
      security:
        - bearerAuth: []     
      responses:
        "200":
          description: Cart deleted succesfully
        "400":
          description: Client Error
        "401":
          description: Unauthorized request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string                  
                    description: Mensaje del tipo de estatus
                    example: error
                  payload:  
                    type: string              
                    description: Mensaje para el tipo de error
                    example: "Error: no auth token"
        "404":
          description: Resource not found
        "422":
          description: Unproccesable Entity
        "500":
          description: Server Error
# ----------------------------------------
components:
  schemas:
    Cart:
      type: object
      properties:
        _id: 
          type: ObjectId
          description: Id autogenerado por mongodb. Es el identificador único para cada producto
        products:
          type: array
          description: Arreglo de productos dentro del carrito
          items:
            type: object 
            properties:
              product:
                type: ObjectId
                description: Id autogenerado por mongodb del producto añadido en el carrito
              quantity:
                type: integer
                format: int64
                minimum: 1
                default: 1
          default: "[]"     
      example:
        _id: ObjectId('asdsadA8-nyhaYvb7-Jgdjsad9-jajhsd')
        products: [{product: ObjectId('653c386cd064ad5e27ae5778'), quantity: 2}, {product: ObjectId('653c3881d064ad5e27ae5781'), quantity: 5}]
  requestBodies:
    updateCart:
      type: object
      properties:
          products:
          type: array
          description: Arreglo de productos dentro del carrito
          items:
            type: object 
            properties:
              product:
                type: ObjectId
                description: Id autogenerado por mongodb del producto añadido en el carrito
              quantity:
                type: integer
                format: int64
                minimum: 1
                default: 1
          default: []       
      example:
        _id: ObjectId('asdsadA8-nyhaYvb7-Jgdjsad9-jajhsd')
        products: "[]"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT    