const EnumErrors = {
  ROUTING_ERROR: 1,
  INVALID_TYPE_ERROR: 2,
  MISSING_VALUE: 3,
  USER_NOT_FOUND: 4,
  PRODUCT_NOT_FOUND: 5,
  INTERNAL_SERVER_ERROR: 6,
  DATABASE_ERROR: 7
}

export default EnumErrors