const EnumErrors = {
  ROUTING_ERROR: 1,
  INVALID_TYPE_ERROR: 2,
  MISSING_VALUE: 3,
  USER_NOT_FOUND: 4,
  RESORUCE_NOT_FOUND: 5,
  INTERNAL_SERVER_ERROR: 6,
  DATABASE_ERROR: 7,
  INVALID_CREDENTIALS: 8,
  NOT_PERMISSIONS: 9
}

export default EnumErrors